## NumPy Array Iterating

- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.

### Iterating 1-D Arrays

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for i in arr:
    print(i, end=" ")

1 2 3 4 5 6 7 8 

### Iterating 2-D Arrays
In a 2-D array it will go through all the rows.

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    print(i, end=" ")

[1 2 3] [4 5 6] 

If we iterate on a n-D array it will go through n-1th dimension one by one.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    for j in i:
        print(j, end=" ")

1 2 3 4 5 6 

### Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print()

for i in arr:
    print(i, end=" ")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]] [[ 7  8  9]
 [10 11 12]] 

In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print()

for i in arr:
    for j in i:
        print(j, end=" ")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[1 2 3] [4 5 6] [7 8 9] [10 11 12] 

In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print()

for i in arr:
    for j in i:
        for k in j:
            print(k, end=" ")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1 2 3 4 5 6 7 8 9 10 11 12 

### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations.
<br><b>It solves some basic issues which we face in iteration</b>

#### (1) Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [26]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.ndim)

for i in np.nditer(arr):
    print(i, end=" ")

3
1 2 3 4 5 6 7 8 

#### (2) Iterating Array With Different Data Types
We can use <b>op_dtypes</b> argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array)
so it needs some other space to perform this action, that extra space is called buffer,
and in order to enable it in nditer() we pass <b>flags=['buffered'].</b>

In [28]:
arr = np.array([1,2,3,4])

for i in np.nditer(arr, op_dtypes="S", flags=['buffered']):
    print(i, end=" ")

b'1' b'2' b'3' b'4' 

#### (3) Iterating With Different Step Size
We can use filtering and followed by iteration.

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x, end=" ")

1 3 5 7 

### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of something one by one.

Sometimes we require corresponding index of the element while iterating, the <b>ndenumerate()</b> method can be used for those usecases.

In [35]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


Enumerate on following 2D array's elements:

In [39]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print()

for idx, x in np.ndenumerate(arr):
    print(idx, x)


[[1 2 3 4]
 [5 6 7 8]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
