## NumPy Array Reshaping
- Reshaping means changing the shape of an array.<br>
- The shape of an array is the number of elements in each dimension.<br>
- By reshaping we can add or remove dimensions or change number of elements in each dimension.<br>

### Reshape From 1-D to 2-D

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
print(arr)
print(arr.shape)

newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.shape)

newarrtwo = arr.reshape(3, 4)
print(newarrtwo)
print(newarrtwo.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


### Reshape From 1-D to 3-D

In [9]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
print(arr)
print(arr.shape)
newarr = arr.reshape(2, 2, 3)
print(newarr)
print(newarr.shape)

newarrtwo = arr.reshape(2, 3, 2)
print(newarrtwo)
print(newarrtwo.shape)

newarrthree = arr.reshape(3, 2, 2)
print(newarrthree)
print(newarrthree.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


### Returns Copy or View?
Check if the returned array is a copy or a view:

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, -1)
print(newarr)
print()
newarrtwo = arr.reshape(2, 2, -1)
print(newarrtwo)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.
